clothbazar/ClothBazar.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClothBazar.Services;
using ClothBazar.Entity;
using ClothBazar.Web.ViewModels;

namespace ClothBazar.Web.Controllers
{
    public class ProductController : Controller
    {
        
        
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search,int? pageNo)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            pageNo = (pageNo.HasValue) ? pageNo.Value > 0 ? pageNo : 1 : 1;
            model.pageNo = pageNo.Value;
            model.searchTerm = search;
            int totalRecords = ProductService.Instance.GetProductCountSolely(search);
            int pageSize = 3;
            
            //model.Products = ProductService.Instance.GetProduct(pageNo.Value);
            model.Products = ProductService.Instance.GetProduct(search, pageNo.Value, pageSize);
          
            model.pager = new Pager(totalRecords, pageNo, pageSize);
            return PartialView(model);


        }

        public ActionResult Create()
        {
           
           List<Category> cat = CategoryService.Instance.GetFeaturedCategory();
           return PartialView(cat);
        }
        [HttpPost]
        public ActionResult Create(CategoryViewModel categoryViewModel)
        {
           
            Product newproduct = new Product();
            newproduct.Name = categoryViewModel.Name;
            newproduct.Description = categoryViewModel.Description;
            newproduct.Price = categoryViewModel.Price;
            newproduct.ImageURL = categoryViewModel.imageURL;
            newproduct.Category = CategoryService.Instance.EditCategory(categoryViewModel.CategoryID);
            

            ProductService.Instance.SaveProduct(newproduct);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            var productByID = ProductService.Instance.EditProduct(ID);
            return PartialView(productByID);
        }
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            ProductService.Instance.UpdateProduct(product);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Delete(int ID)
        {
            var product = ProductService.Instance.EditProduct(ID);
            ProductService.Instance.DeleteProduct(product.ID);
            return RedirectToAction("ProductTable");
        }

        public ActionResult Detail(int ID)
        {
            ProductDetails model = new ProductDetails();
            model.Pdetails = ProductService.Instance.EditProduct(ID);
            return View(model);
        }


        
    }
}

clothbazar/ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                //var newImage = new Image() { Name = fileName };

                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

clothbazar/ClothBazar.Web/Views/Product/Create.cshtml
@model List<Category>
@{
    ViewBag.Title = "Product(Create)";
}

<h2>Product</h2>
<form id="CreateForm">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var item in Model)
                    {
                        <option value="@item.ID">@item.Name</option>
                    }

                </select>
                <br />
            </div>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" />
                <br />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" />
                <br />
            </div>
            <div class="form-group">

                <label>Price</label>
                <input class="form-control" name="Price" />
                <br />
            </div>
            <br />
            <input class="form-control" id="imageUpload" type="file" />

            <button id="saveBtn" type="button">Save</button>
            <button id="cancelBtn" type="button">Cancel</button>

        </div>
        <div class="col-md-4">
            <input name="ImageURL" id="ImageURL" type="hidden" />

            <img src="~/Content/images/shop/images.png" style="width:550px; height:300px;" id="productImage">
        </div>
    </div>   
</form>
<script>

    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#productImage").attr("src", response.ImageURL);


            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });

    $("#cancelBtn").click(function () {
        $("#newContainer").html("");
        focusAnimation();
    });

    $("#saveBtn").click(function() 
    {
        $.ajax({
            type: "POST",
            url: "/Product/Create",
            data:$("#CreateForm").serialize()
        })
         .done(function (response) {
             console.log(response);
             $("#tableContainer").html(response);
             $("#newContainer").html("");
         })
         .fail(function (HMLHttpRequest,textStatus,errorThrown) {
             alert("FAIL");
         });

    }
    );

    function focusAnimation() {

        $('html,body').animate({
            scrollTop: $('#tableContainer').offset().top - 100
        }, 1000);
    }
</script>

clothbazar/ClothBazar.Web/Views/Product/Edit.cshtml
@model Product
@{
    ViewBag.Title = "Product(Edit)";
}
<form id="CreateForm" class="form-group">
    <div class="row">
        <div class="col-md-8">
            <h2>Edit Product</h2>
            <input type="hidden" name="ID" value="@Model.ID" />
            <label>Name</label>
            <input class="form-control" name="Name" value="@Model.Name" />
            <br />
            <label>Description</label>
            <input class="form-control" name="Description" value="@Model.Description" />
            <br />

            <label>Price</label>
            <input class="form-control" name="Price" value="@Model.Price" />
            <br />
            <input class="form-control" id="imageUpload" type="file" />
            <br />
            <button id="updateBtn" type="button">Update</button>
            <button id="cancelBtn" type="button">Cancel</button>
        </div>
        <div class="col-md-4">
            <input name="ImageURL" id="ImageURL" type="hidden" value="@Model.ImageURL" />
            @if (Model.ImageURL == null)
            {
                <img src="~/Content/images/shop/images.png" style="width:550px; height:300px;" id="productImage">
            }
            else
            {
                <img src="@Model.ImageURL" style="width:550px; height:300px;" id="productImage">
            }
          
        </div>
    </div>



</form>
<script>

    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#productImage").attr("src", response.ImageURL);


            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });


    $("#cancelBtn").click(function () {
        $("#CreateForm").html("");
        focusAnimation();
    });

    $("#updateBtn").click(function ()
    {
        $.ajax({
            type: "POST",
            url: "/Product/Edit",
            data: 
                $("#CreateForm").serialize()
            
        })
         .done(function (response) {
             $("#tableContainer").html(response);
             $("#newContainer").html("");
         })
         .fail(function (HMLHttpRequest,textStatus,errorThrown) {
             alert("FAIL");
         });
    });

    function focusAnimation() {
        $('html,body').animate({
            scrollTop: $('#productTables').offset().top - 100
        },1000);
    }
</script>

clothbazar/ClothBazar.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Product(Home)";
   
}

<div class="row">
    <div class="col-md-12">
        <div class="title-section">
            <h2 class="title">
                Product
            </h2>
        </div><!-- /.title-section -->
    </div><!-- /.col-md-12 -->
</div>

<div class="container">

    <div id="tableContainer">
        @{
            Html.RenderAction("ProductTable");

        }
    </div>
    <hr />
    <div id="newContainer">

    </div>
    <hr />
    <div id="editCategory">

    </div>
</div>

clothbazar/ClothBazar.Web/Views/Product/ProductTable.cshtml
@model ClothBazar.Web.ViewModels.ProductSearchViewModel
@{
    ViewBag.Title = "ProductTable";
}

@*<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>*@
<div>
    <div class="form-group">
        <form method="post">
           
               
                   <div class="row">
                       <div class="col-md-8">
                          
                           <input placeholder="search" class="form-control" id="searchTxt" />
                       </div>
                       <div class="col-md-4">
                           <button type="button" id="searchBtn">Search</button>
                           <button type="button" id="newBtn">New</button>
                       </div>
                   </div>
                       
                   
            
            
            
           
        </form>

        
    </div>

    <h2>ProductTable</h2>
    @if (Model.Products != null && Model.Products.Count >0)
    {
        <table id ="productTables" class="table table-striped">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Category</td>
                    <td>Price</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>

                @foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>
                            @if (product.Category != null)
                            {
                                <text>@product.Category.Name</text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@product.Price</td>

                        <td>
                            <button type="button" class="edit" data-id="@product.ID">Edit</button>
                            <button type="button" class="delete" data-id="@product.ID">Delete</button>
                            <button type="button" class="addToCart" data-id="@product.ID">Add To Cart</button>

                        </td>
                    </tr>
                }

            </tbody>
        </table>
   
    }
    else
    {
        <div>No Product Found</div>
    }
    <div>
        @if (Model.pager != null && Model.pager.TotalPages > 1)
        {
            if (Model.pager.CurrentPage > 1)
            {
                <button class="pageBtn" data-pageno="1">FirstPage</button>
                <button class="pageBtn" data-pageno="@(Model.pager.CurrentPage-1)">PreviousPage</button>
            }
            for (var page = Model.pager.StartPage; page <= Model.pager.EndPage; page++)
            {
                var isActive = @Model.pager.CurrentPage == page ? "btn-info active" : string.Empty;
                <button class="@isActive pageBtn" data-pageno="@page">@page</button>
            }

            if (Model.pager.CurrentPage < Model.pager.EndPage)
            {
                <button class="pageBtn" data-pageno="@(Model.pager.EndPage)">LastPage</button>
                <button class="pageBtn" data-pageno="@(Model.pager.CurrentPage + 1)">NextPage</button>
            }

        }


    </div>
    
</div>
<div id="EditTable">

</div>
<script>
    //$('#productTables').DataTable();
    
    $(".pageBtn").click(function () {
       
        $.ajax({
            url: '@Url.Action("ProductTable","Product")',
            data: {
                pageNo: $(this).attr('data-pageno'),
                search:'@Model.searchTerm'
            }


        })
        .done(function (response) {
           
            $("#tableContainer").html(response);
        })
         .fail(function (XMLHttpRequest, textStatus, errorThrown) {


         });
    });


    $("#searchBtn").click(function () {
       var searchValue = $("#searchTxt").val();
       $.ajax( {
           url:'@Url.Action("ProductTable","Product")',
           data: {
               search: searchValue
           }

           
       })
       .done(function (response) {
           console.log(response);
           $("#tableContainer").html(response);
       })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            

        });
    });

    $("#newBtn").click(function () {
        
        $.ajax({
            url: "/Product/Create"
        })
        .done(function (response) {
          
            $("#newContainer").html(response);
            focusAction();
        })
         .fail(function (XMLHttpRequest, textStatus, errorThrown) {
             alert("FAIL");

         });
    });

    $(".edit").click(function () {
       
        $.ajax({
            
            url: "/Product/Edit",
            data: {
                ID: $(this).attr('data-id')
            }
        })
        
         .done(function (response) {
             $("#EditTable").html(response);
             focusAction2();
         })
         .fail(function (XMLHttpRequest,textStatus,errorThrown) {
             alert("FAIL;")
         });
        
    })
    $(".delete").click(function () {
        var product = confirm("Are you sure you want to delete this Product?");
        if (product)
        {
            $.ajax({
                type: 'GET',
                url: '/Product/Delete',
                data: {
                    ID: $(this).attr('data-id')
                }

            })
        .done(function (response) {
            
            $("#tableContainer").html(response);

        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {

        });
        }
       

    })

    function focusAction() {
        $('html,body').animate({
            scrollTop: $("#newContainer").offset().top - 100
        }, 1000);

    }

    function focusAction2() {
        $('html,body').animate({
            scrollTop: $("#EditTable").offset().top - 100
        }, 1000);

    }

    var products = [];
    $('.addToCart').click(function () {

        var pID = $(this).attr('data-id');
        alert(pID);
        products.push(pID);
        $.cookie('addToCartCookie', products.join('-'));
       
    })
</script>