clothbazar/ClothBazar.Web/ViewModels/CheckOutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ClothBazar.Entity;
using ClothBazar.Web.Models;

namespace ClothBazar.Web.ViewModels
{
    public class CheckOutViewModel
    {
        public List<Product> cartProducts { get; set; }
        public List<int> ProductID { get; set; }
        public ApplicationUser User { get; set; }
    }
}

clothbazar/ClothBazar.Web/ViewModels/ShopViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ClothBazar.Entity;

namespace ClothBazar.Web.ViewModels
{
    public class FilterProductViewModel
    {
        public List<Category> categoryList { get; set; }
        public List<Product> products { get; set; }
        public int? CatID { get; set; }
        public int? sortByNumber { get; set; }
        public decimal maxPrice { get; set; }
        public Pager pager { get; set; }
        public int pageSize { get; set; }

        public string searchTerm { get; set; }
    }

    public class SliderFilterProductViewModel
    {
        public List<Product> filterProduct { get; set; }
        public Pager pager { get; set; }
        public int? SortBy { get; set; }
        public int? CategoryID { get; set; }      
    }

}

clothbazar/ClothBazar.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClothBazar.Services;
using ClothBazar.Entity;
using ClothBazar.Web.ViewModels;

namespace ClothBazar.Web.Controllers
{
    public class ProductController : Controller
    {
        
        
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search,int? pageNo)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            pageNo = (pageNo.HasValue) ? pageNo.Value > 0 ? pageNo : 1 : 1;
            model.pageNo = pageNo.Value;
            model.searchTerm = search;
            int totalRecords = ProductService.Instance.GetProductCountSolely(search);
            int pageSize = 3;
            
            //model.Products = ProductService.Instance.GetProduct(pageNo.Value);
            model.Products = ProductService.Instance.GetProduct(search, pageNo.Value, pageSize);
          
            model.pager = new Pager(totalRecords, pageNo, pageSize);
            return PartialView(model);


        }

        public ActionResult Create()
        {
           
           List<Category> cat = CategoryService.Instance.GetFeaturedCategory();
           return PartialView(cat);
        }
        [HttpPost]
        public ActionResult Create(CategoryViewModel categoryViewModel)
        {
           
            Product newproduct = new Product();
            newproduct.Name = categoryViewModel.Name;
            newproduct.Description = categoryViewModel.Description;
            newproduct.Price = categoryViewModel.Price;
            newproduct.ImageURL = categoryViewModel.imageURL;
            newproduct.Category = CategoryService.Instance.EditCategory(categoryViewModel.CategoryID);
            

            ProductService.Instance.SaveProduct(newproduct);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            var productByID = ProductService.Instance.EditProduct(ID);
            return PartialView(productByID);
        }
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            ProductService.Instance.UpdateProduct(product);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Delete(int ID)
        {
            var product = ProductService.Instance.EditProduct(ID);
            ProductService.Instance.DeleteProduct(product.ID);
            return RedirectToAction("ProductTable");
        }

        public ActionResult Detail(int ID)
        {
            ProductDetails model = new ProductDetails();
            model.Pdetails = ProductService.Instance.EditProduct(ID);
            return View(model);
        }


        
    }
}

clothbazar/ClothBazar.Web/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClothBazar.Services;
using ClothBazar.Web.ViewModels;
using ClothBazar.Entity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
namespace ClothBazar.Web.Controllers
{
    
    public class ShopController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryId, int? sortBy, int? pageNo)
        {
            FilterProductViewModel model = new FilterProductViewModel();
               pageNo = (pageNo.HasValue) ? pageNo.Value > 0 ? pageNo : 1 : 1;
               model.pageSize = 6;
               model.searchTerm = searchTerm;
               int count = ProductService.Instance.GetProductCount(searchTerm, minimumPrice, maximumPrice, categoryId);
            model.categoryList = CategoryService.Instance.GetCategoryHavingProduct();
            model.products = ProductService.Instance.ProductsForShopPage(searchTerm, maximumPrice, minimumPrice, categoryId, sortBy, pageNo.Value, model.pageSize);
            model.CatID = categoryId;
            model.sortByNumber = sortBy;
            model.maxPrice = ProductService.Instance.GetMaxPrice();
            model.pager = new Pager(count, pageNo, model.pageSize);
           

            return View(model);

        }

        public ActionResult FilterProduct(string searchTerm, int? filteredmaximumPrice, int? filteredminimumPrice, int? categoryId, int? sortBy, int? pageNo)
          {
              SliderFilterProductViewModel model = new SliderFilterProductViewModel();
              int pageSize = 6;
              pageNo = (pageNo.HasValue) ? pageNo.Value > 0 ? pageNo : 1 : 1;
              model.filterProduct = ProductService.Instance.ProductsForShopPage(searchTerm, filteredmaximumPrice, filteredminimumPrice, categoryId, sortBy, pageNo.Value, pageSize);
             
              decimal maxPrice = ProductService.Instance.GetMaxPrice();
              int? minimumPrice = (filteredminimumPrice.HasValue) ? filteredminimumPrice.Value != 0 ? filteredminimumPrice : 0 : 0;
              decimal? maximumPrice = (filteredminimumPrice.HasValue) ? filteredmaximumPrice.Value == maxPrice ? maxPrice : filteredmaximumPrice.Value : 0;
              
              model.SortBy = sortBy;
              model.CategoryID = categoryId;

              int count = ProductService.Instance.GetProductCount(searchTerm, minimumPrice, maximumPrice, categoryId);
              model.pager = new Pager(count, pageNo, pageSize);

              return PartialView(model);

          }
        // GET: Shop
        [Authorize]
        public ActionResult CheckOut()
        {
            CheckOutViewModel model = new CheckOutViewModel();

           var cartProduct = Request.Cookies["myAddToCartCookie"];
            if (cartProduct != null && !string.IsNullOrEmpty(cartProduct.Value))
           {
               var cartProducts = cartProduct.Value;
               var cartItemInString = cartProducts.Split('-');
               List<int> cartItem = cartItemInString.Select(x =>int.Parse(x)).ToList();
               model.cartProducts = ProductService.Instance.GetCartProduct(cartItem);
               model.ProductID = cartItem;
               model.User = UserManager.FindById(User.Identity.GetUserId());
           }
            return View(model);
        }

        public JsonResult PlaceOrder(string Products)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            if (!string.IsNullOrEmpty(Products)) 
            {
                
                Orders orders = new Orders();
                var a = Products.Split('-').ToList();
                var b = a.Select(x => int.Parse(x)).ToList();
                var ProductIDs = a.Select(x => int.Parse(x)).Distinct().ToList();
                orders.userID = User.Identity.GetUserId();
                orders.status = "Pending";
                orders.dateTime = DateTime.Now;
                List<Product> cartProduct = ProductService.Instance.GetCartProduct(ProductIDs);
                orders.totalAmount = cartProduct.Sum(x => x.Price * (b.Where(y => y == x.ID).Count()));
                orders.orderItems = new List<OrderItems>();
                orders.orderItems.AddRange(cartProduct.Select(x => new OrderItems() { ProductID = x.ID, quantity = (b.Where(y => y == x.ID).Count()) }));
                int rowseffected = ShopService.Instance.SaveOrder(orders);

                result.Data = new { Success = true, Rows = rowseffected };
            }
           else
            {
                result.Data = new { Success = false };
            }

           return result;
        }
    }
}

clothbazar/ClothBazar.Web/Views/Shop/CheckOut.cshtml
@model ClothBazar.Web.ViewModels.CheckOutViewModel
@{
    ViewBag.Title = "CheckOut";
}

@*<h2>CheckOut</h2>
@if (Model.cartProducts != null)
{
    
    foreach (var product in Model.cartProducts)
    {
        var quantity = @Model.ProductID.Where(x => x == product.ID).Count();
        <div>Name :@product.Name - Price: @product.Price - Quantity : @quantity - Total : @(product.Price * Model.ProductID.Where(x => x == product.ID).Count()) </div>

    }
    <div>Total Bill : @Model.cartProducts.Sum(x => x.Price * Model.ProductID.Where(y => y==x.ID).Count())</div>

}
else
{
    <h1>Cart is empty</h1>
}*@
@if (Model.cartProducts != null)
{
    var i = 1;
    <div class="container">
        <div class="row">
            <div class="col-md-4 order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <span class="badge badge-secondary badge-pill">3</span>
                </h4>

                <ul class="list-group mb-3">


                    @foreach (var item in Model.cartProducts)
                    {
                        
                        var quantity = @Model.ProductID.Where(x => x == item.ID).Count();
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">@i) @item.Name - Qty (@quantity)</h6>
                                <small class="text-muted">@(item.Description.Length > 100 ? item.Description.Substring(0,99)+ "................" : item.Description)</small>
                            </div>
                            <span class="text-muted">@item.Price</span>
                        </li>
                        i++;
                    }




                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total (USD)</span>
                        <strong>Total Bill : @Model.cartProducts.Sum(x => x.Price * Model.ProductID.Where(y => y == x.ID).Count())</strong>
                    </li>
                </ul>


            </div>
            <div class="col-md-8 order-md-1">
                <h4 class="mb-3">Billing address</h4>
                <form class="needs-validation" novalidate="">
                    <div class="row">
                        <div class="col-md-12">
                            <label for="Name">Name</label>
                            <input type="text" class="form-control" id="Name" placeholder="" value="@Model.User.Name" required="">
                           
                        </div>
                    
                    </div>
   

             

                    <div class="mb-3">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" placeholder="you@example.com" value="@Model.User.Email">
                       
                    </div>

                    <div class="mb-3">
                        <label for="address">Address</label>
                        <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="" value="@Model.User.Address">
                       
                    </div>
                    <button id="PlaceOrderBtn" class="btn btn-primary btn-lg btn-block" type="button">Place Order</button>
                </form>
            </div>
        </div>
    </div>
    <script>
    $('#PlaceOrderBtn').click(function () {
        debugger;
        $.ajax({
            url: '@Url.Action("PlaceOrder","Shop")',
            data: {
                Products: '@string.Join("-", Model.ProductID)'
            }
        })
        .done(function (response) {
            if (response.Success) {
                $.cookie('myAddToCartCookie', '');
                cartCount();
                alert("Your order has been placed successfully");
                window.location = '@Url.Action("Index","Shop")';
            }
            else {
                alert("Sorry your order is unable to place");
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {

        })

    });
    </script>
}
else
{
<div class="container">
    <h3 style="margin-bottom:350px;margin-top:20px">No Product in shopping cart.</h3>
</div>

}

clothbazar/ClothBazar.Web/Views/Shop/FilterProduct.cshtml
@model SliderFilterProductViewModel

<div class="filter-shop clearfix">
    <p class="showing-product float-right">
        
        Showing @(((Model.pager.CurrentPage - 1) * Model.pager.PageSize) + 1) – @(((Model.pager.CurrentPage - 1) * Model.pager.PageSize) + (Model.filterProduct.Count < Model.pager.PageSize ? Model.filterProduct.Count : Model.pager.PageSize)) of @Model.pager.TotalItems Products
    </p>
</div><!-- /.filte-shop -->

    <div class="product-content product-threecolumn product-slidebar clearfix">
        <ul class="product style2 sd1">
        
            @foreach (var item in Model.filterProduct)
            {
                <li class="product-item">
                    <div class="product-thumb clearfix">
                        <a href="@Url.Action("Detail", "Product", new { ID = item.ID })">
                            <img src="@item.ImageURL" alt="image">
                        </a>
                        <span class="new">New</span>
                    </div>
                    <div class="product-info clearfix">
                        <span class="product-title">@item.Description</span>
                        <div class="price">
                            <ins>
                                <span class="amount">$@item.Price</span>
                            </ins>
                        </div>
                    </div>
                    <div class="add-to-cart text-center">
                        <a class="myAddToCart" data-id="@item.ID" href="#">ADD TO CART</a>
                    </div>
                    <a href="#" class="like"><i class="fa fa-heart-o"></i></a>
                </li>

            }
        

        </ul><!-- /.product -->
    </div><!-- /.product-content -->
    <div class="product-pagination text-center clearfix">
        <ul class="flat-pagination">
            @if (Model.pager != null)
            {
                if (Model.pager.CurrentPage > 1)
                {
                    <li class="prev">
                        <a data-href="@Url.Action("FilterProduct", "Shop", new { pageNo = Model.pager.CurrentPage - 1, sortBy = Model.SortBy, categoryID = Model.CategoryID })" class=" pageDataLink"><i class="fa fa-angle-left"></i></a>
                    </li>
                }

            

                for (var page = Model.pager.StartPage; page <= Model.pager.EndPage; page++)
                {
                    string activeClass = Model.pager.CurrentPage == page ? "active bg-info" : string.Empty;

                    <li class="@activeClass"><a data-href="@Url.Action("FilterProduct", "Shop", new { pageNo = page, sortBy = Model.SortBy, categoryID = Model.CategoryID })" title="" class="pageDataLink">@page</a></li>
                }

                if (Model.pager.CurrentPage < Model.pager.TotalPages)
                {
                    <li><a data-href="@Url.Action("FilterProduct", "Shop", new { pageNo = Model.pager.CurrentPage + 1, sortBy = Model.SortBy, categoryID = Model.CategoryID })" class="pageDataLink"><i class="fa fa-angle-right"></i></a></li>
                }
               
            }

        </ul><!-- /.flat-pagination -->
    </div>

<input type="hidden" id="sortBy" value="@Model.SortBy"/>
<input type="hidden" id="categoryId" value="@Model.CategoryID" />
<script>
    $('.pageDataLink').click(function () {
       
        var url = $(this).attr('data-href');
        if (url != "" && url != undefined)
        {
            PriceRangeChange(url);
        }
        
    });
    //var products = [];
    $('.myAddToCart').click(function () {
        
        cartCount();
        var pID = $(this).attr('data-id');
        alert('Product is added to cart');
        products.push(pID);
        $.cookie('myAddToCartCookie', products.join('-'));
        $('#cartProductCount').html(products.length);
       
    });
</script>

clothbazar/ClothBazar.Web/Views/Shop/Index.cshtml
@using ClothBazar.Web.ViewModels;
@using ClothBazar.Web.Code;
@model FilterProductViewModel
@{ViewBag.Title = "Shop";}
<!-- Page title -->
<div class="page-title parallax parallax1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title-heading">
                    <h1 class="title">SHOP</h1>
                </div><!-- /.page-title-heading -->
                @*<div class="breadcrumbs">
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li><a href="shop-3col.html">Shop</a></li>
                            <li><a href="shop-3col-slide.html">Slidebarshop</a></li>
                        </ul>
                    </div> /.breadcrumbs*@
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.page-title -->

<section class="flat-row main-shop shop-slidebar">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="sidebar slidebar-shop">
                    <div class="widget widget-search">
                        <form role="search" method="get" class="search-form" action="@Url.Action("Index", "Shop")">
                            <label>
                                <input type="search" class="search-field" placeholder="Search …" value="@Model.searchTerm" name="searchTerm">
                            </label>
                            <input type="submit" class="search-submit" value="Search">
                        </form>
                    </div><!-- /.widget-search -->
                    <div class="widget widget-sort-by">
                        <h5 class="widget-title">
                            Sort By
                        </h5>
                   
             
                   
                  
                      
                        <ul>
                            <li><a class="dataLink @(Model.sortByNumber.HasValue?Model.sortByNumber==(int)SortByEnum.Default?"active":string.Empty:string.Empty)" data-href="@Url.Action("FilterProduct", "Shop", new { sortBy = (int)SortByEnum.Default, CategoryID = Model.CatID})">Default-Newness</a></li>
                            <li><a class="dataLink @(Model.sortByNumber.HasValue?Model.sortByNumber==(int)SortByEnum.Popularity?"active":string.Empty:string.Empty)" data-href="@Url.Action("FilterProduct", "Shop", new { sortBy = (int)SortByEnum.Popularity, CategoryID = Model.CatID })">Popularity</a></li>
                            <li><a class="dataLink @(Model.sortByNumber.HasValue?Model.sortByNumber==(int)SortByEnum.PriceLowToHigh?"active":string.Empty:string.Empty)" data-href="@Url.Action("FilterProduct", "Shop", new { sortBy = (int)SortByEnum.PriceLowToHigh, CategoryID = Model.CatID })">Price: low to high</a></li>
                            <li><a class="dataLink @(Model.sortByNumber.HasValue?Model.sortByNumber==(int)SortByEnum.PriceHighToLow?"active":string.Empty:string.Empty)" data-href="@Url.Action("FilterProduct", "Shop", new { sortBy = (int)SortByEnum.PriceHighToLow, CategoryID = Model.CatID })">Price: high to low</a></li>
                        </ul>
                    </div>
                    <div class="widget widget_tag">
                        <h5 class="widget-title">
                            Tags
                        </h5>
                   
                        <div class="tag-list">
                           
                         @*@{
                             var isActiveed = !(@Model.CatID.HasValue) ? "active" : string.Empty;
                            <a class="dataLink" data-href="@Url.Action("FilterProduct", "Shop", new { sortBy = Model.sortByNumber })">All products</a>
                        }*@  
                            
                           
                            @foreach (var item in Model.categoryList)
                            {

                              
                                <a class="dataLink" data-href="@Url.Action("FilterProduct", "Shop", new { CategoryID = item.ID, sortBy = Model.sortByNumber })">@item.Name</a>


                            }
                        </div>
                        <!-- /.widget-sort-by -->

                        <div class="widget widget-price">
                            <h5 class="widget-title">Filter by price</h5>
                            <div class="price-filter">
                                <div id="slide-range"></div>
                                <p class="amount">
                                    Price: <input type="text" id="amount" disabled="">
                                </p>
                            </div>
                        </div>
                    <div> <a href="@Url.Action("Index", "Shop")"><button class="btn-danger">Reset Filter</button></a></div>
                    </div><!-- /.widget -->
                </div><!-- /.sidebar -->
            </div><!-- /.col-md-3 -->
            <div class="col-md-9">
               
                <div id="productDiv">
                    @{
                        var SliderFilterProductViewModel = new SliderFilterProductViewModel();
                        SliderFilterProductViewModel.filterProduct = Model.products;
                        SliderFilterProductViewModel.pager = Model.pager;
                        SliderFilterProductViewModel.CategoryID = Model.CatID;
                        SliderFilterProductViewModel.SortBy = Model.sortByNumber;
                        Html.RenderPartial("FilterProduct", SliderFilterProductViewModel);
                    }

                </div>

                
            </div><!-- /.col-md-9 -->
        </div><!-- /.row -->
    @*</div><!-- /.container -->*@
</section><!-- /.flat-row -->

<script>
    
  
    
    var callTimeout;
    var priceSlider = $("#slide-range").slider({
        
        range: true,
        min: 0,
        max: @Model.maxPrice,
        values: [0, @Model.maxPrice],
        slide: function (event, ui) {
            
            var minPrice = ui.values[0];
            var maxPrice = ui.values[1];
            $("#amount").val("$" + minPrice + ".00" + " - " + "$" + maxPrice + ".00");
            clearTimeout(callTimeout);
           // callTimeout =  setTimeout(getMyData,500);
            callTimeout = setTimeout(getMyData, 500);
          
        
         
         
        }
    });

 
    function PriceRangeChange(dUrl){
       
        $.ajax({
            url:dUrl ,
            data: {
                sortBy:$('#sortBy').val(),
                categoryId:$('#categoryId').val(),
                filteredminimumPrice : priceSlider.slider("values", 0),
                filteredmaximumPrice : priceSlider.slider("values", 1)
            }
        })
        .done(function (response) {
            $("#productDiv").html(response);
          
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    }


    $('.dataLink').click(function () {
       
        var url = $(this).attr('data-href');
        if (url != "" && url != undefined)
        {
            
            PriceRangeChange(url);
            
        
        
        }});

        function getMyData(minPrice,maxPrice){
            {
                console.log("getMyDataCalled");
                $.ajax({
               
                    url: "/Shop/FilterProduct",
                    data: {
                        sortBy:$('#sortBy').val(),
                        categoryId:$('#categoryId').val(),
                   
                        filteredminimumPrice:priceSlider.slider("values",0),
                        filteredmaximumPrice:priceSlider.slider("values",1)
                    }

                })
            .done(function (response) {
         
                $("#productDiv").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {

            });
            }
        }


    
</script>